### ISSUE TITLE
Compilation warning: "no rule to process file"

### ISSUE THREAD

**Issue by kattouf** [yandex/vgsl#1]
<img width="906" alt="Screenshot 2024-06-21 at 15 17 34" src="https://github.com/yandex/vgsl/assets/7829589/102914e4-2251-488e-9c6d-a72fabbcf5b9">

```
no rule to process file '/Users/kattouf/Development/aviasales-ios/Pods/VGSLBase/BasePublic/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64'

```

Для исправления стоит исключить `PrivacyInfo.xcprivacy` из `source_files` в [VGSLBase.podspec](https://github.com/yandex/vgsl/blob/main/Specs/VGSLBase/5.1.0/VGSLBase.podspec)
[Похожая проблема](https://github.com/airbnb/lottie-ios/pull/2307)

**Comment by rsbooster** [comment]
Поправлены подспеки в релизе 5.1.1. В остальном, он не отличается от 5.1.0.
